language: node_js
node_js:
  - 0.8
  - 0.10
services:
  - mongodb
  - redis
  - couchdb
  - mysql
  - postgresql
before_script:
  - curl -X PUT localhost:5984/database_cleaner
  - mysql -e 'create database database_cleaner;'
  - createdb database_cleaner
