sudo: false
language: node_js
node_js:
  - 8
  - node
  - lts/*
services:
  - mongodb
  - redis
  - couchdb
  - mysql
  - postgresql
  - elasticsearch
before_script:
  - curl -X PUT localhost:5984/database_cleaner
  - mysql -e 'create database database_cleaner;'
  - createdb database_cleaner
