sudo: false
language: node_js
node_js:
  - 6.0
  - 6.1
  - 6.2
  - 6.3
services:
  - mongodb
  - redis
  - couchdb
  - mysql
  - postgresql
  - elasticsearch
before_script:
  - curl -X PUT localhost:5984/database_cleaner
  - mysql -e 'create database database_cleaner;'
  - createdb database_cleaner
